# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christopher Rodell
title: Ph.D. Student in Atmospheric Science
email: crodell@eoas.ubc.ca
website: https://github.com/cerodell

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  cerodell
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: christopher-rodell-bba8911b4
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Weather Research Forecast Team
  icon: fas fa-globe
  url: https://wfrt.eoas.ubc.ca/#


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. Student in Atmospheric Science at the University of British Colombia. Originally from Colorado, I obtained a BA in Physical Geography and a BA in Atmospheric and Oceanic Sciences from the University of Colorado, Boulder. During that time, I also have earned a certificate in weather forecasting from Penn State University. My research interests include coupled atmosphere-wildland fire behavior modeling, forest fuel moisture forecasts, wildfire smoke forecasting, and field observations of controlled burns.  A current project of mine is developing a Numerical Weather Prediction derived <a target="_blank" href="https://cerodell.github.io/fwf-docs/build/html/index.html">Fire Weather Forecast Model</a> to assess the moisture content within varied layers of the forest fuels (vegetation). My outside interests include snowboarding, climbing, backpacking, and biking.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of British Columbia Vancouver
        caption: 2019 - Present
        sub_title: Ph.D. Atmospheric Sciences

        quote: >
            - David Bates Scholarship 2019 <br>
            - W.H. Mathews Scholarship 2020
        # description: | # this will include new lines to allow paragraphs
        #   Research Assistant in the Department of Earth, Ocean and Atmospheric Sciences

      - layout: top-middle
        title: University of Colorado Boulder
        caption: 2017 - 2018 <br> 2008 - 2013
        sub_title: B.A. Atmospheric and Oceanic Sciences <br> B.A. Physical Geography 
        quote: >
          - Dean’s list: Fall 2017/Spring 2018 <br>
          - Undergraduate Research Fellow: Characterizing Thunderstorm <br> Outflow Boundaries in Complex Terrain
        # description: | # this will include new lines to allow paragraphs
        #   Research Assistant in the Department of Earth, Ocean and Atmospheric Sciences

      - layout: top-middle
        title: Pennsylvania State University
        caption: 2015 -2016
        sub_title: Certificate in Weather Forecasting
        # quote: >
        # description: | # this will include new lines to allow paragraphs



  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of British Columbia
        link: https://www.eoas.ubc.ca/
        link_text: Department of Earth Oceanic and Atmospheric Sciences
        sub_title: Graduate Research Assistant
        caption: 2019 - Present
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - Developing a Numerical Weather Prediction derived <a target="_blank" href="https://cerodell.github.io/fwf-docs/build/html/index.html">Fire Weather Forecast Model</a> to assess the moisture content within varied layers of the forest fuels (vegetation) for daily use by operational wildland firefighters.
          - This forest fuel moisture forecast is being integrated into a new fire growth and fuel emissions model to aid in smoke forecast predictions in the <a target="_blank" href="https://firesmoke.ca">Bluesky Canada</a> smoke forecast system. 
          - I have constructed a low-cost, in situ instrument to observe and profile the vertical concentration of PM2.5 in wildfire smoke plumes. This disposable <a target="_blank" href="https://cerodell.github.io/fire_sensors/ ">Particulate Matter Sensor</a> will hopefully help my research team better understand wildfire smoke dynamics and forecasting. 


      - layout: left
        title: University of Colorado
        link: https://www.colorado.edu/atoc/
        link_text: Department of Atmospheric and Oceanic Sciences
        sub_title: Undergraduate Research Opportunity Fellow
        caption: Sept. 2017 - Feb. 2019
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - Assisting Dr. Katja Friedrich and Nicholas Luchetti (Ph.D. student) in evaluating thunderstorm outflow boundaries in WRF-Fire. 
          - My tasks included detecting and analyzing 26 observed outflow boundaries in the Colorado Front Range for the purposes of validating WRF’s ability to accurately model gust fronts.
          - Analyzed the characteristics of each individual outflow boundary using a variety of remote sensing and in-situ instruments. 
          Depth, length, propagation speed/direction, temperature/pressure change, turbulence, and maximum velocity throughout the boundary layer were quantified and categorized depending on the thunderstorm type, terrain, and ambient atmospheric conditions. 
          - <a target="_blank" href="http://clouds.colorado.edu/fire/">For more information</a>                                                            

  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: U.S. Forest Service
        link: https://www.fs.usda.gov/whiteriver
        link_text: White River National Forest
        caption: Nov. 2015 - Feb. 2017
        sub_title: Sampling Officer
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - Collected precipitation samples for the <a target="_blank" href="http://nadp.slh.wisc.edu/>National Atmospheric Deposition Program</a> (NADP).
          - Obtained digital and physical samples from two gauge sites located at an elevation of approximately 11,800 feet.
          - Commuted to each location on snowmobile or utility terrain vehicle (UTV) to ensure the NADP received data to support their research.
          - Digital and physical samples collected and transmitted to NADP included data from a NOAH IV rain gauge and a non contaminated weighed precipitation sample.
          - Gauge sites also required routine equipment maintenance and on occasion emergency repairs were required (regardless of weather conditions).

  - title: Additional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: U.S. Forest Service
        link: https://www.fs.usda.gov/whiteriver
        link_text: White River National Forest
        caption: May 2015 - Oct. 2016
        sub_title: Forestry Technician GS-05-Trails Crew
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - Responsible for maintaining a diverse trail network located in arid desert and high alpine locations. 
          - The level of trail repair and maintenance varied in each climatic zone as a result of variable soil composition and respected rates of erosion. 
          - Dispatched for days at a time in remote areas where the only way to communicate was via satellite phone. 
          - Extended assignments required on the spot creative problem solving with limited resources.
          - The work was dangerous and strenuous requiring the use of varied safety measures. 
          - Completed USFS National Fire Response training and was dispatched to fight multiple fires in 2016 fire season.
      
      - layout: left
        title: U.S. Forest Service
        link: https://www.fs.usda.gov/whiteriver
        link_text: White River National Forest
        caption: May 2014 - Nov. 2014
        sub_title: Forestry Technician GS-04-Developed Rec.
        # quote: |
          # Forestry Technician GS-04-Developed Rec.
        description: | # this will include new lines to allow paragraphs
          - The Maroon Bells, located approximately 5 miles from Aspen CO, is the most visited scenic area in one of the most visited National Forests in the Nation. 
          - Helped mitigate the damage to the area from overuse by educating the visitors through public contact. 
          - Strong communication skills were required as I often met people from foreign countries with limited or no English language skills.  


  - title: Publications and Conference Presentations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Publications
        description: |
          - Luchetti, N. T., Friedrich, K. & <b>Rodell, C. E.</b> Evaluating Thunderstorm Gust Fronts in New Mexico and Arizona. Mon. Weather Rev. 4943–4956 (2020) https://doi.org/10.1175/MWR-D-20-0204.1
          - Thompson, D.K., Schroeder, D., Wilkinson, S.L., Barber, Q., Baxter, G., Cameron, H., Hsieh, R., Marshall, G., Moore, B., Refai, R., <b>Rodell, C.</b>, Schiks, T., Verkaik, G.J., Zerb, J., 2020: Recent Crown Thinning in a Boreal Black Spruce Forest Does Not Reduce Spread Rate nor Total Fuel Consumption: Results from an Experimental Crown Fire in Alberta, Canada. Fire, 3, 28. (https://doi.org/10.3390/fire3030028.)
          - Luchetti, N. T., Friedrich, K. & <b>Rodell, C. E</b> & Lundquist, J. K. Characterizing thunderstorm gust fronts near complex terrain. Mon. Weather Rev. 148, 3267–3286 (2020).
          - <b>Rodell, C.</b>, R. Howard, R. Stull, 2021: A Fire Weather Index Forecast System for Canada. (In Preparation 2021)
          - Philip, S. Y.,  Kew S. F.,  Jan van Oldenborgh G.,  Yang W., Vecchi G. A.,  Anslow F. S.,  Li S.,  Seneviratne S. I. ,  Luu L. N.,  Arrighi J.,  Singh R.,  Aalst M., Hauser M., Schumacher D. L.,  Marghidan C. P., Ebi K. L.,  Bonnet R., Vautard R., Tradowsky J., Coumou D., Lehner F., Wehner M., <b>Rodell, C.</b>, Stull R., Howard R., Gillett N., Otto F. E. L. Rapid attribution analysis of the extraordinary heatwave on the Pacific Coast of the US and Canada June 2021 . 119–123 (In Preparation 2021).

      - layout: top-middle
        title: Oral Presentations
        description: |
         - <b>Rodell, C.</b>, Moisseeva, N., Howard, R., Stull, R., Schigas, R., Chui, T. (18-21 Nov 2019): Plume rise and dispersion: BlueSky Canada, Research and field observations.  Wildland Fire Canada 2019.  Ottawa, ON. 
         - Moisseeva, N., Howard, R., <b>Rodell, C.</b>, Stull, R., 12 Feb 2020: Wildfire behavior and smoke research at UBC.  BC Environment Interagency Air Quality meeting.  ECCC Vancouver.  (f2f)
         - Moisseeva, N., Howard, R., <b>Rodell, C.</b>, Stull, R., 19 Mar 2020: Wildfire behavior and smoke research at UBC.  Natural Resources Canada, Edmonton. (online)
         - Moisseeva, N., Howard, R., <b>Rodell, C.</b>, Stull, R., 14 April 2020: Wildfire behavior and smoke research at UBC. Forest Fire Working Group Meeting. (online)
         - Stull, R., Moisseeva, N., Howard, R., <b>Rodell, C.</b>, 15 April 2020: Wildfire behavior and smoke research at UBC. Cascadia Wildfire and Urban Smoke Working Group. (online)
         - Moisseeva, N., Howard, R., <b>Rodell, C.</b>, Stull, R., 18 April 2020: Wildfire behaviour and smoke research at UBC: Research Leading to Improvement in Operational Smoke and Fire Index Forecasting. Forest Fire Working Group Meeting, ECCC. (remote) 
         - Moisseeva, N., Howard, R., <b>Rodell, C.</b>, Stull, R., 10 June 2020: Wildfire behaviour and smoke research at UBC: Research Leading to Improvement in Operational Smoke and Fire Index Forecasting. BC Wildfire. (remote)
         - Moisseeva, N., Howard, R., Schmidt, T., Deere, A., Schigas, R., <b>Rodell, C.</b>, Stull, R., 7 July 2020: Wildfire behaviour and smoke research at UBC: Update. Natural Resources Canada. (remote)
         - <b>Rodell, C.</b>, Moisseeva, N., Howard, R., Stull, R., 18 September 2020: Particulate Matter Sensors: Vertical Profile of a Wildland Fire Smoke Plume by In-situ Observation. Atmospheric Chemistry Research Group, UBC. (remote)
         - <b>Rodell, C.</b>, Moisseeva, N., Howard, R., Stull, R., 2 Nov. 2020: Fire Weather Forecasts: Numerical Weather Prediction Derived Fire Weather Index System. Government of the Northwest Territories, Fort Smith, NT. (remote)
         - <b>Rodell, C.</b>, Moisseeva, N., Howard, R., Stull, R., 14 April 2021: Particulate Matter Sensors: Vertical Profile of a Wildland Fire Smoke Plume by In-situ Observation. United States Forest Service AirFire Research Group, Seattle, USA. (remote)
         - <b>Rodell, C.</b>, Moisseeva, N., Howard, R., Stull, R., May 13th 2021:  Numerical weather prediction (NWP) derived Canadian Fire Weather Indices (FWI). American Meteorological Society 13th Fire and Forest Meteorology Symposium. (remote)
         - <b>Rodell, C.</b>, Moisseeva, N., Chui, T., Howard, R., Stull, R., June 3rd 2021: Improving the Spatial and Temporal Resolution of the Existing Fire Weather Index System for Operational Use by Wildfire Agencies. Canadian Meteorological and Oceanographic Society 55th Congress. (remote)
         - Moisseeva, N., <b>Rodell, C.</b>, Wang, J., Howard, R., Chui, T., Schigas, R., Stull, R., 2 June 2021: The Evaluation of Numerically-Driven Wildfire Smoke Plume Rise and Fire Behaviour System. 55th CMOS Congress. (remote)
                
      - layout: top-middle
        title: Posters Presentations
        description: |
          - <b>Rodell, C.</b>, N. Luchetti.,  K. Friedrich J. Lundquist, B. Kosovic, 2018: Characterizing Thunderstorm Outflow Boundary in Complex Terrain. Earth System and Space Science Poster Conference. November, 2018, Boulder, CO. 
          - Luchetti, N. T., K. Friedrich, <b>C .Rodell</b>, J. Lundquist, B. Kosovic, 2018: Evaluating Gust Front Interactions With Idealized Terrain in WRF-Fire. Earth System and Space Science Poster Conference. November, 2018, Boulder, CO.   
          - Luchetti, N. T.,  K. Friedrich, <b>C .Rodell</b>, J. Lundquist, B. Kosovic, 2018: Characterizing Thunderstorm Outflow Boundary in Complex Terrain. 29th American Meteorological Society Conference on Severe and Local Storms, October, 2018, Stowe, VT.
          - Luchetti, N. T., K. Friedrich, <b>C .Rodell</b>, J. Lundquist, B. Kosovic, 2017: Evaluating Thunderstorm Outflow Boundaries in WRF-Fire. Earth System and Space Science Poster Conference. November, 2017, Boulder, CO.  


  - title: Technical Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Programing
        quote: >
          <b>Python, JAVASCRIPT/HTML/CSS, Bash, Unix/Linux,  <br>
          Arduino, C ++, MATLAB, IDL, NCL, Julia, R <br> 
          VSCode, Git</b>

      - layout: top-middle
        title: Modeling
        quote: >
          <a target="_blank" href ="https://www.mmm.ucar.edu/weather-research-and-forecasting-model">Weather Research Forecast Model (WRF)</a> <br>
          <a target="_blank" href ="https://wiki.openwfm.org/wiki/Open_Wildland_Fire_Modeling_E_community_Wiki">Weather Research Forecast Model SFIRE (WRF-SFIRE)</a> <br>
          <a target="_blank" href ="https://sites.google.com/firenet.gov/wfaqrp-airfire/data/bluesky">Bluesky Smoke Forecast Model</a> <br>
          <a target="_blank" href ="https://www.ready.noaa.gov/HYSPLIT.php">HYSPLIT</a> <br>
        
  
  - title: Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - National Wildfire Coordinating Group 
      - FEMA Incident Command System               	  
      - National Incident Management System   		      	  
      - B Intermediate Sawyer Crosscut                          
      - Trailer Towing 			                                        	  
      - Equipment Operator, Snowmobile/UVT                       
      - Wilderness First Aid / CPR 
      - American Institute for Avalanche Research and Education   (AIARE Level 1)      


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
