# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christopher Rodell
title: Ph.D. Student in Atmospheric Science
email: crodell@eoas.ubc.ca
website: https://github.com/cerodell

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  cerodell
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: christopher-rodell-bba8911b4
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: firesmoke.ca
  icon: fas fa-globe
  url: https://firesmoke.ca/forecasts/fireweather/current/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. Student in Atmospheric Science at the University of British Colombia. Originally from Colorado, I obtained a BA in Physical Geography and a BS in Atmospheric and Oceanic Sciences from the University of Colorado, Boulder. During that time, I also received a certificate in weather forecasting from Penn State University. My research interests are coupled atmosphere-wildland fire behavior modeling, forest fuel moisture forecasts, wildfire smoke forecasting, and field observations of controlled burns.  A current project is developing a Numerical Weather Prediction derived <a href="https://cerodell.github.io/fwf-docs/build/html/index.html">Fire Weather Forecast Model</a> to assess the moisture content within varied layers of the forest fuels (vegetation). My outside interests include snowboarding, climbing, backpacking, and biking.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of British Columbia Vancouver
        caption: 2019 - Present
        sub_title: Ph.D. Atmospheric Sciences
        # caption: 2019 - 2020
        # sub_title: M.S.  Atmospheric Sciences
        quote: >
          Since 1915, UBC has evolved into a leading centre for teaching, learning and research, consistently ranked among the top 20 public universities in the world and recently recognized as North America’s most international university. As our influence and global community grow, so does our obligation to maintain excellent brand standards.        
        description: | # this will include new lines to allow paragraphs
          Research Assistant in the Department of Earth, Ocean and Atmospheric Sciences

      - layout: left
        title: University of Colorado Boulder
        caption: 2017 - 2018 <br> 2008 - 2013
        sub_title: B.A. Atmospheric and Oceanic Sciences <br> B.A. Physical Geography 
        quote: >
          Since 1915, UBC has evolved into a leading centre for teaching, learning and research, consistently ranked among the top 20 public universities in the world and recently recognized as North America’s most international university. As our influence and global community grow, so does our obligation to maintain excellent brand standards.        
        description: | # this will include new lines to allow paragraphs
          Research Assistant in the Department of Earth, Ocean and Atmospheric Sciences

      - layout: left
        title: Pennsylvania State University
        caption: 2015 -2016
        sub_title: Certificate in Weather Forecasting
        quote: >
          Since 1915, UBC has evolved into a leading centre for teaching, learning and research, consistently ranked among the top 20 public universities in the world and recently recognized as North America’s most international university. As our influence and global community grow, so does our obligation to maintain excellent brand standards.        
        description: | # this will include new lines to allow paragraphs
          Research Assistant in the Department of Earth, Ocean and Atmospheric Sciences



  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: U.S. Forest Service
        caption: Nov. 2015 - Feb. 2017
        sub_title: Sampling Officer <br> White River National Forest
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Collected precipitation samples for the National Atmospheric Deposition Program (NADP).
          - Every Tuesday, regardless of weather conditions, I obtained digital and physical samples from two gauge sites located at an elevation of approximately 11,800 feet. 
          - Commuted to each location on snowmobile or utility terrain vehicle (UTV) to ensure the NADP received data to support their research. 
          - Digital and physical samples collected and transmitted to NADP included data from a NOAH IV rain gauge and a non contaminated weighed precipitation sample. 
          - Gauge sites also required routine equipment maintenance and on occasion emergency repairs were required (regardless of weather conditions).
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
